### ISSUE TITLE
Touch Drag events are not working

### ISSUE THREAD

**Issue by krazyjakee** [abdavid/jslider#10]
The example here works fine: http://egorkhmelev.github.io/jslider/

But on my site, the slider refuses to work on IOS/Android.

Are then any options I am supposed to pass or not pass to get this working?

```javascript
priceSlider.slider({
  from: 0,
  to: 10,
  step: 1,
  smooth: true,
  limits: true,
  dimension: '&pound;'
});
```

Here is the site with slider on the home page: https://newportcaravans.proofing2.nexusos.co.uk/search

On mobile, press the show advanced search to reveal the sliders.

**Comment by abdavid** [comment]
It has nothing to do with the configuration. I suspect this is because of changes to how HammerJS works. 
I know there has been some changes there, so you might want to pull an earlier version if its not working correctly on mobile. Try tag v2.0.1 while I resolve this.

**Comment by abdavid** [comment]
Do a clone from master and see if it works like intended now. :+1: 

If it works for you then ill create a new tag.

**Comment by krazyjakee** [comment]
This is fixed, thanks a lot dude!
