### ISSUE TITLE
MathHelper not defined in minified bundle

### ISSUE THREAD

**Issue by krazyjakee** [abdavid/jslider#11]
Here's a minimal example referencing the minified bundle and the error (in the console): http://jsfiddle.net/gt07ft2c/

> MathHelper is not defined

**Comment by abdavid** [comment]
I can confirm this. It is not missing in jquery.slider-bundled.js

I will have a look at the minification process. Thanks!

**Comment by abdavid** [comment]
Should be fixed in master now.

**Comment by krazyjakee** [comment]
Yup, fixed.
