### ISSUE TITLE
Far left side sets an empty value

### ISSUE THREAD

**Issue by krazyjakee** [abdavid/jslider#12]
I think this bug has existed in all previous versions so I'm not sure if it's a bug or a feature.

1. Let's say we have a double slider of 1;10
1. Initially it starts at 2;9
1. The user drags 2 down to 1 (far left) so now the value is 1;9
1. The value sent (through get request) and the value set in the html is `?value=%3B9` (;9)
1. It should be 1;9

The issue is that if I pass the GET request value directly back into jslider for persistance, it throws a fatal error you can see in the console here: http://jsfiddle.net/gt07ft2c/1/ (caused by the empty first value passed in the html).

**Comment by krazyjakee** [comment]
I don't have the tools to compile this project, but here is my proposed fix for this: https://github.com/krazyjakee/jslider/commit/6be78d1050ba90392025e74db97571e11cc4b81f

**Comment by abdavid** [comment]
You should be able to do a npm install & bower install and just do a grunt dev / grunt build from the commandline to build the project. I am currently on vacation, but I will have a look at the change when I get back.

**Comment by krazyjakee** [comment]
I spent hours previously trying to install/build/compile grunt and it just refuses on osx. I tried again but to avail.

Enjoy your holiday!
