### ISSUE TITLE
Sliders become "linked"

### ISSUE THREAD

**Issue by krazyjakee** [abdavid/jslider#13]
Here is an example: http://jsfiddle.net/pqtq4zy7/

After playing around with the sliders, they become linked (dragging one slider drags the other).

**Comment by wasik** [comment]
I've noticed this too; I'm on windows 8.1 and have verified using chrome & firefox.

If you drag the top slider, then the second slider (with the left handle), the top slider continues to drag (even though I'm only dragging the bottom slider).

**Comment by abdavid** [comment]
@wasik could you paste the config you are using with jslider?

**Comment by wasik** [comment]
I was able to reproduce the linking in the jsfiddle example @krazyjakee posted above, so I recommend taking a look there. But to answer your question, here is my code:

  $("#slider_1").slider({ from: 5, to: 500, heterogeneity: ['50/50', '75/175'], limits: true, step: 1, dimension: '', skin: "round" });
  $("#slider_2").slider({ from: 0, to: 250, heterogeneity: ['50/100'], limits: true, step: 1, dimension: '', skin: "round" });

**Comment by wasik** [comment]
Hi @abdavid - I just tested out the jsfiddle example ( http://jsfiddle.net/pqtq4zy7/ ) on a different Mac computer (10.10.4) with both Chrome 43 and Safari 8.0.7 and verified the problem exists there too, so it's not just a Windows problem. 

I suspect this impacts anyone who has multiple sliders on the same page.

**Comment by abdavid** [comment]
I will have a look at it. Just got a newborn baby so I cant really say when. 

From the sound of your research it might be related to jQuery instances being scoped improperly.

- David

**Comment by wasik** [comment]
Congratulations!! Obviously that comes first :) Good luck getting enough sleep.

**Comment by wasik** [comment]
@abdavid  - please take your time with the family; this post isn't meant to be a rush for you, but I thought I'd share some findings publicly for anyone else interested.

If I only keep my mouse pointer directly above the handles, the problem goes away. It's when I release the mouse pointer not directly above the handle that the sliders get 'linked'.

It's almost like the 'mouseUp' event isn't being recognized or acted on if the mouse button is released not directly over the handle.

I've managed to reproduce the error, linking 3 separate sliders, by always releasing the mouse button when the pointer is not directly over the handle. Example: http://jsfiddle.net/pqtq4zy7/2/

**Comment by wasik** [comment]
I just noticed something else - it works fine on my phone, presumably due to some difference with touch events. I'm only noticing the bug on my desktop (both on windows 8 with chrome/IE and mac osx safari). 

Let me know if you'd like a video to show how they get linked whenever you're back into things, or if you're able to reproduce on your own. Thanks!

**Comment by wasik** [comment]
Hi @abdavid - I hope all is well with the family. Any estimates as to when you'll be able to investigate the sliders getting linked?

**Comment by abdavid** [comment]
@wasik - Thanks, everything is well with the family! Sleep is still an issue though, but I recon I should be able to have a look at this issue during the coming weekend if my calendar does not betray me. 

I did some initial testing on my phone IOS 8.4.1 latest safari and chrome. But like you mentioned in an above post - This does not seem to effect touch actions but rather vanilla mouse actions. 

If you had a small video of the bug that would be much appreciated. 

- David

**Comment by wasik** [comment]
From what I've heard about sleep, when they become teenagers you'll have to pull them out of bed. ...but we're not there yet either :) Good luck.

I took a video of me using Chrome (on a macbook pro) and linking the sliders. I first linked them (by releasing the mouse button not directly on top of the handle), then unlink them (by releasing the button directly on top of the handle), then I link them all again a 3rd time.

https://youtu.be/DiJanDO2owo

**Comment by abdavid** [comment]
From what I can see the issue must reside here. One way to fix this would be to resolve a container passed through the event object and determine if the container by compare would be equal to this.$el.

E.g.
```javascript
this.bind(jQuery(document), Draggable.EVENT_MOVE, (event:any)=> {
    var container = jQuery(event.currentTarget).parent('someParentSelector');
    if(container !== this.$el) {
       return;
    }
    ...
});				

this.bind(jQuery(document), Draggable.EVENT_DOWN, (event:any)=> {
var container = jQuery(event.currentTarget).parent('someParentSelector');
    var container = jQuery(event.currentTarget).parent('someParentSelector');
    if(container !== this.$el) {
       return;
    }				
    ...
});
````

**Comment by wasik** [comment]
So that would prevent the move/down events from occuring on non-selected sliders. ...but I think we might still be missing the "mouse up" event when you release the mouse button outside of a handle.

Is there some way to capture all "mouse button release" events and then trigger the appropriate 'mouse up' handlers? I think that may be the piece that's missing (but I'm far from an expert) :)

**Comment by wasik** [comment]
There's some chance I was able to fix this just by updating where the EVENT_UP handler gets attached to. I attached it to $("body") instead of this.$el

It seems to fix the problem as I was seeing it on jsfiddle, but I'm not sure if that introduces other problems.

http://jsfiddle.net/pqtq4zy7/12/

**Comment by abdavid** [comment]
Nice catch @wasik, that was exactly what was needed to fix the issue.
