### ISSUE TITLE
<%= and %> confuse the rails asset pipeline

### ISSUE THREAD

**Issue by wasik** [abdavid/jslider#14]
This is specific to my use case (with Ruby on Rails) but the Rails asset pipeline is getting confused with "<%= ... %>" in the javascript files and is attempting to process them.

I have replaced those markers with <X= and X> and it seems to work nicely. Perhaps that's a change other people could benefit from too?

**Comment by wasik** [comment]
I replaced <%= and %> with:
&lt;X= and X&gt;
But that didn't show up in the original post

**Comment by abdavid** [comment]
@wasik could you pull from master and give me some feedback on if this works for you?

**Comment by wasik** [comment]
This works - thanks!

**Comment by abdavid** [comment]
:+1:
