### ISSUE TITLE
Be able to 'connect' single handle sliders to the left

### ISSUE THREAD

**Issue by wasik** [abdavid/jslider#16]
It would be great if the "<i class="v"></i>" part of a single-handle slider could be connected to the left so we could style it and color in the selected area. (similar to http://refreshless.com/nouislider/slider-options/#section-Connect )

This is a feature request, not a bug, but figured I'd mention it anyway. Feel free to close/ignore.

**Comment by abdavid** [comment]
This is now default. If one should not wish to style the connected part to the left, the stylesheet should control this. Appropriate css classes exists for necessary scope.
