### ISSUE TITLE
sample index.html seems to be dead

### ISSUE THREAD

**Issue by enuggetry** [abdavid/jslider#21]
since no jquery and hammer was included in the bundle, I just added the CDNs.

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>

But, the result was the samples were all dead widgets (can't drag slider bars, just stuck).
no console errors.

**Comment by abdavid** [comment]
Issue should be resolved now. Thanks for reporting
