### ISSUE TITLE
Bundle with HammerJS is problematic

### ISSUE THREAD

**Issue by eirikhm** [abdavid/jslider#8]
Please consider creating a separate build that ships without HammerJS bundled. 

The whole code should also be wrapped so it does not pollute global scope. Hammer2 cannot run alongside the current project.

**Comment by abdavid** [comment]
Ill have a look at it at some time later today.

**Comment by abdavid** [comment]
For now the lib will ship with a HammerJS dependency. I recon you guys are having trouble upgrading to HammerJS2? 

The lib is now enclosed in a namespace so it doesn't pollute global scope.
