### ISSUE TITLE
Option to prefix the dimension rather than append

### ISSUE THREAD

**Issue by krazyjakee** [abdavid/jslider#9]
We're using currency rather than a measurement so seeing a label like this: 1000£ isn't really correct.
It should be like this £1000.

**Comment by abdavid** [comment]
I am actually thinking about removing this support. Instead I see it as ideal to let users do this with :before and :after in CCS3. 

There is already a lot of configuration options for this slider implementation, and I want to slim it down some more.

**Comment by krazyjakee** [comment]
That makes sense, thanks!
